### PR TITLE
feat(bridge): add last restart to bridge

### PR DESCRIPTION
**Pull request by jkurz**
* add container last restartTime to bridge overview page

### CODE REVIEW

**Review by wilsonodk — CHANGES_REQUESTED** [review]
How about making it a bit more human-readable?

`Oct 27, 2017, 6:15:40 PM EDT` vs `2017-10-27T23:15:40Z`

**Review by jtolsma — APPROVED** [review]

**Comment by jkurz** [comment]
updated @wilsonodk

**Review by wilsonodk — APPROVED** [review]
If you did… 

```js
lastRestart = (new Date(container.lastState.terminated.finishedAt)).toLocaleString();
```

…you wouldn't have to do the substring stuff.

+ `toLocaleString`: `'9/11/2017, 10:06:52 AM'`

+ `toString + substring`: `'Mon Sep 11 2017 10:06:52'`

Just a thought.

**Comment by jkurz** [comment]
@wilsonodk updated

**Pull request merged**
