### PR TITLE
Hot fix: Clone

### PR DESCRIPTION
**Pull request by wilsonodk**
Hot fix for clone issue where large payloads are getting clipped. 

Instead of using Harbor API, use ShipIt's bulk endpoint.

### CODE REVIEW

**Review by jhodnett2 — APPROVED** [review]

**Comment by jkurz** [comment]
Very nice. Much easier than we thought. This is for shipyard also or just for clones?

**Comment by wilsonodk** [comment]
Just for clones. Would be pretty easy to do for Shipyard as well.

**Comment by wilsonodk** [comment]
Was thinking of waiting for a non-hot fix to do that.

**Review by jkurz — APPROVED** [review]

**Comment by jkurz** [comment]
yeah go ahead and merge and cherry pick back into develop.

**Review by jtolsma — APPROVED** [review]

**Pull request merged**
