### PR TITLE
fix(events): show shipment events when they exist

### PR DESCRIPTION
**Pull request by wilsonodk**
Check if there are events in HelmIt, if they are, display them. Warnings are given a amber color, Errors are given a red color. This check happens every 5 minutes.

Also added a interval check for the Shipment status that appear at the top of the page so that they will clear if the issue clear (without needing a page reload).

screen shot 2018-01-25 at 4 32 14 pm

screen shot 2018-01-25 at 4 32 47 pm

### CODE REVIEW

**Review by jtolsma — APPROVED** [review]
This will be an awesome feature

**Comment by jritsema** [comment]
Is this on the overview tab?  To keep the overview page fast, wondering if we should move this out on to its own "events" tab or maybe at the top of the logs tab?

**Comment by wilsonodk** [comment]
@jritsema It is on the Overview tab. The idea is that these messages, when present, provide a TON of value about why your Shipment isn't running correctly. I feel like if we move them to another tab they will not be seen.

Keep in mind, that most of the time there are no events. Also, the call to get the events is async.

**Comment by wilsonodk** [comment]
Updated the verbiage on the Shipment Events when there are no events, and…
screen shot 2018-01-29 at 12 59 48 pm

…when there are:
screen shot 2018-01-29 at 12 58 38 pm

**Pull request merged**
