### PR TITLE
add shipment load balancer status

### PR DESCRIPTION
**Pull request by wilsonodk**
Show the Load Balancer status when the there is an outage.

Resolves issue [7](https://github.com/turnerlabs/harbor/issues/7)

### CODE REVIEW

**Comment by jkurz** [comment]
Testing this out, when I trigger, the status does not automatically show up. I have to refresh the page to see the loadbalancer status.

**Comment by jkurz** [comment]
If my load balancer is failing, returning a 503 origin unhealthy. the loading box still shows up. Maybe we should have a different message and no loading box to the user as they may think it's still working.

**Comment by wilsonodk** [comment]
Can you show me an example of the 503 error?

**Comment by wilsonodk** [comment]
@jkurz Fixed both issues.

**Comment by jkurz** [comment]
Very nice. I tested all the use cases I can think of. Things seem to be working very well.

**Comment by jkurz** [comment]
LGTM

**Pull request merged**
